### PR TITLE
changing the default for the creation of config/db.php

### PR DESCRIPTION
**Pull request by gonzalez**

### CODE REVIEW

**Comment by rshade** [comment]
This should be done in attributes/default.rb

**Comment by cdwilhelm** [comment]
what will happen if that is changed to false?  how does it effect the db.php and any other behavior?
might want to check the docs and cookbook readme also need to be changed
I understand the issue, but I think the change might have a bigger impact.  and more research and testing needs to go into the change
instead of changing the cookbook, changing the attribute in the rightscript for kabam would be safest

**Comment by rshade** [comment]
changing it to false in default.rb will cause it to not be written. I am fine with that as it's a hangover from a lot earlier, and I have yet to have a client use it. We can then update it to true in a wrapper and set the location for clients that want that functionality.

**Comment by cdwilhelm** [comment]
still need to verify the cookbook readme and docs.rightscale.com overview and tutorial to make sure no changes are needed there.

**Comment by rshade** [comment]
@gonzalez can you fix?

**Pull request closed without merging**
