### PR TITLE
Chef 12 azure rm support

### LINKED ISSUE #29: chef 12 azure rm support
per @rgeyer 

rgeyer [11:50 AM]  
So.. This is what’s failing for the PHP app server in AzureRM due to the ohai deficiencies there. I wonder.. Why are we being specific about the IP it listens on? Why not listen on `0.0.0.0/0`?

https://github.com/rightscale-cookbooks/rs-application_php/blob/master/libraries/helper.rb#L65-L83

[11:54]  
Ahh wait.. I see.. We only use it for tagging..

https://github.com/rightscale-cookbooks/rs-application_php/blob/master/recipes/tags.rb#L30-L35

### PR DESCRIPTION
**Pull request by rshade**
azure rm support, closes #29

### CODE REVIEW

**Comment by rgeyer** [comment]
LGTM. I've been testing many of these changes in isolation getting PFTv2 updated and working.

**Comment by rshade** [comment]
Finished verifying <default-centos-68> (0m11.56s).
-----> Destroying <default-centos-68>...
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <default-centos-68> destroyed.
       Finished destroying <default-centos-68> (0m7.45s).
       Finished testing <default-centos-68> (6m56.33s).
-----> Kitchen is finished. (6m59.11s)

**Comment by rshade** [comment]
```
Finished verifying <default-ubuntu-1204> (0m12.39s).
-----> Destroying <default-ubuntu-1204>...
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <default-ubuntu-1204> destroyed.
       Finished destroying <default-ubuntu-1204> (0m8.38s).
       Finished testing <default-ubuntu-1204> (6m52.52s).```

**Comment by rshade** [comment]
```
Finished verifying <default-ubuntu-1404> (0m11.13s).
-----> Destroying <default-ubuntu-1404>...
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <default-ubuntu-1404> destroyed.
       Finished destroying <default-ubuntu-1404> (0m8.06s).
       Finished testing <default-ubuntu-1404> (8m29.93s).
-----> Kitchen is finished. (8m33.72s)```

**Comment by rshade** [comment]
```
      Finished verifying <default-centos-72> (0m11.63s).
-----> Destroying <default-centos-72>...
       ==> default: Forcing shutdown of VM...
       ==> default: Destroying VM and associated drives...
       Vagrant instance <default-centos-72> destroyed.
       Finished destroying <default-centos-72> (0m8.58s).
       Finished testing <default-centos-72> (8m34.14s).
-----> Kitchen is finished. (8m37.28s)```

**Pull request merged**
